<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1</name>
   <tag></tag>
   <elementGuidId>d76f2131-d48a-42e3-b907-c666960715b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-select-value-1']/span/mat-select-trigger/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-select-trigger.ng-tns-c132-1.ng-star-inserted > div.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>308b0ec5-ab7c-420b-a2e8-2ede44d0e816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>f9ec7b6d-3cbf-40e6-a3fe-a7002cd61e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> +1 </value>
      <webElementGuid>9044b031-9878-408c-8b3e-e5205031329f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-1&quot;)/span[@class=&quot;mat-select-value-text ng-tns-c132-1 ng-star-inserted&quot;]/mat-select-trigger[@class=&quot;ng-tns-c132-1 ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>e2b6c8e1-5095-44c2-bd0f-89f96a6333d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-1']/span/mat-select-trigger/div</value>
      <webElementGuid>8df9e414-4ab5-46b3-ac3a-7ad3fb6d41bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[16]</value>
      <webElementGuid>71c7fc02-5086-4a19-8371-658a4d917ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::div[8]</value>
      <webElementGuid>0e3011fa-e741-4e69-9b2e-e2b61fb5da76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+1']/parent::*</value>
      <webElementGuid>c62e5d6f-610f-46cc-b1d4-a1cf15699302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-select-trigger/div</value>
      <webElementGuid>cbbe9205-5f72-4baa-942e-55d3c4e7b54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' +1 ' or . = ' +1 ')]</value>
      <webElementGuid>24759da7-9574-47fd-9903-7f1e80e7c48c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
