<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Remember me</name>
   <tag></tag>
   <elementGuidId>18e40eee-551a-432d-9403-5720afeddcb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-checkbox[@id='login-rememberMe']/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.mat-checkbox-layout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>391d13b3-2ff6-4cba-812b-95b9548ee73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-checkbox-layout</value>
      <webElementGuid>f763b538-be72-4aaa-a474-a15bb85b93d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>login-rememberMe-input</value>
      <webElementGuid>529802a8-99a4-404a-a7f6-7b32a7a38899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Remember me</value>
      <webElementGuid>4439f484-c2a9-454f-8114-ee3555e42540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-rememberMe&quot;)/label[@class=&quot;mat-checkbox-layout&quot;]</value>
      <webElementGuid>4186a4cc-18e0-444c-a908-c1e700e482f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='login-rememberMe']/label</value>
      <webElementGuid>2bd494be-a722-41fa-bbe8-8ef4658aa02d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::label[1]</value>
      <webElementGuid>590738a1-a2bf-46b2-9417-0c2be033007f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::label[1]</value>
      <webElementGuid>d84e7e36-d9aa-4b1a-a1eb-4b17d74751dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>7d9c4063-5512-491c-a88b-1b0377792e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '  Remember me' or . = '  Remember me')]</value>
      <webElementGuid>f61a7159-686d-479d-9610-24e49384e9eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
